### ISSUE TITLE
Decorating Videos with Features

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/seneca-odd-catalog#5]
View caching introduced a bug that removed video decoration of features from org and device.

**Comment by kixxauth** [comment]
Gonna keep this one open. We need a systematic approach.

From Erik:

> Dan and I triple checked and when a video's attributes.player is an empty object, we can't parse it. We should be throwing an exception there, but we're sort-of swallowing the error and returning null for the view, which causes the crash. tl;dr we expect the player feature to have at least a type attr

We need to build a version of the Levin apps that we can use to hit staging and get the homepage view (they need to auth) before we're going to be able to fix this.
